"""removing primary key indexes

Revision ID: 01c0880003fa
Revises: b2cc59137ab1
Create Date: 2025-06-23 19:26:31.158749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c0880003fa'
down_revision: Union[str, Sequence[str], None] = 'b2cc59137ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_tasks_task_no'), table_name='daily_tasks')
    op.create_index(op.f('ix_daily_tasks_day'), 'daily_tasks', ['day'], unique=False)
    op.drop_index(op.f('ix_task_status_log_id'), table_name='task_status')
    op.create_index(op.f('ix_task_status_task_no'), 'task_status', ['task_no'], unique=False)
    op.create_index(op.f('ix_task_status_user_id'), 'task_status', ['user_id'], unique=False)
    op.drop_index(op.f('ix_tasks_day'), table_name='tasks')
    op.create_unique_constraint(None, 'tasks', ['day'])
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index(op.f('ix_users_latest_task'), 'users', ['latest_task'], unique=False)
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_latest_task'), table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.drop_constraint(None, 'tasks', type_='unique')
    op.create_index(op.f('ix_tasks_day'), 'tasks', ['day'], unique=True)
    op.drop_index(op.f('ix_task_status_user_id'), table_name='task_status')
    op.drop_index(op.f('ix_task_status_task_no'), table_name='task_status')
    op.create_index(op.f('ix_task_status_log_id'), 'task_status', ['log_id'], unique=False)
    op.drop_index(op.f('ix_daily_tasks_day'), table_name='daily_tasks')
    op.create_index(op.f('ix_daily_tasks_task_no'), 'daily_tasks', ['task_no'], unique=False)
    # ### end Alembic commands ###
