"""removing unnecessary indexes

Revision ID: 6441818c8000
Revises: f334f4aecbe9
Create Date: 2025-06-20 18:43:15.433277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6441818c8000'
down_revision: Union[str, Sequence[str], None] = 'f334f4aecbe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_description'), table_name='tasks')
    op.drop_index(op.f('ix_users_team'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_team'), 'users', ['team'], unique=False)
    op.create_index(op.f('ix_tasks_description'), 'tasks', ['description'], unique=False)
    # ### end Alembic commands ###
