"""updating nullable and unique constraints

Revision ID: 7e4d36bd3e4a
Revises: ec9aabe9cbe1
Create Date: 2025-06-20 16:13:57.434793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4d36bd3e4a'
down_revision: Union[str, Sequence[str], None] = 'ec9aabe9cbe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_tasks', 'day',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_daily_tasks_task'), table_name='daily_tasks')
    op.create_index(op.f('ix_daily_tasks_task'), 'daily_tasks', ['task'], unique=True)
    op.alter_column('task_status', 'log_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('task_status', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_status', 'task_no',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_status', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_tasks_day'), table_name='tasks')
    op.create_index(op.f('ix_tasks_day'), 'tasks', ['day'], unique=True)
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=True)
    op.alter_column('users', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'team',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('users', 'latest_task',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.alter_column('users', 'latest_task',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'team',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.drop_index(op.f('ix_tasks_day'), table_name='tasks')
    op.create_index(op.f('ix_tasks_day'), 'tasks', ['day'], unique=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('task_status', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('task_status', 'task_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_status', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_status', 'log_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_daily_tasks_task'), table_name='daily_tasks')
    op.create_index(op.f('ix_daily_tasks_task'), 'daily_tasks', ['task'], unique=False)
    op.alter_column('daily_tasks', 'day',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
