"""correcting indexes

Revision ID: b2cc59137ab1
Revises: 687191d70b7a
Create Date: 2025-06-23 19:21:17.484438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2cc59137ab1'
down_revision: Union[str, Sequence[str], None] = '687191d70b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_tasks_day'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_task'), table_name='daily_tasks')
    op.create_unique_constraint(None, 'daily_tasks', ['task'])
    op.drop_index(op.f('ix_task_status_status'), table_name='task_status')
    op.drop_index(op.f('ix_task_status_task_no'), table_name='task_status')
    op.drop_index(op.f('ix_task_status_user_id'), table_name='task_status')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.create_unique_constraint(None, 'tasks', ['title'])
    op.drop_index(op.f('ix_users_latest_task'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.create_index(op.f('ix_users_latest_task'), 'users', ['latest_task'], unique=False)
    op.drop_constraint(None, 'tasks', type_='unique')
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=True)
    op.create_index(op.f('ix_task_status_user_id'), 'task_status', ['user_id'], unique=False)
    op.create_index(op.f('ix_task_status_task_no'), 'task_status', ['task_no'], unique=False)
    op.create_index(op.f('ix_task_status_status'), 'task_status', ['status'], unique=False)
    op.drop_constraint(None, 'daily_tasks', type_='unique')
    op.create_index(op.f('ix_daily_tasks_task'), 'daily_tasks', ['task'], unique=True)
    op.create_index(op.f('ix_daily_tasks_day'), 'daily_tasks', ['day'], unique=False)
    # ### end Alembic commands ###
