"""existing db with a company table

Revision ID: ec9aabe9cbe1
Revises: e051c71326d2
Create Date: 2025-06-20 16:00:39.832191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec9aabe9cbe1'
down_revision: Union[str, Sequence[str], None] = 'e051c71326d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_index(op.f('ix_test_table_day'), table_name='test_table')
    op.drop_index(op.f('ix_test_table_task'), table_name='test_table')
    op.drop_index(op.f('ix_test_table_task_no'), table_name='test_table')
    op.drop_table('test_table')
    op.alter_column('daily_tasks', 'day',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_daily_tasks_day'), 'daily_tasks', ['day'], unique=False)
    op.create_index(op.f('ix_daily_tasks_task'), 'daily_tasks', ['task'], unique=False)
    op.create_index(op.f('ix_daily_tasks_task_no'), 'daily_tasks', ['task_no'], unique=False)
    op.alter_column('task_status', 'log_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('task_status', 'task_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_status', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.create_index(op.f('ix_task_status_log_id'), 'task_status', ['log_id'], unique=False)
    op.create_index(op.f('ix_task_status_status'), 'task_status', ['status'], unique=False)
    op.create_index(op.f('ix_task_status_task_no'), 'task_status', ['task_no'], unique=False)
    op.create_index(op.f('ix_task_status_user_id'), 'task_status', ['user_id'], unique=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('tasks_day_title_key'), 'tasks', type_='unique')
    op.create_index(op.f('ix_tasks_day'), 'tasks', ['day'], unique=False)
    op.create_index(op.f('ix_tasks_description'), 'tasks', ['description'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.alter_column('users', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'team',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.create_index(op.f('ix_users_latest_task'), 'users', ['latest_task'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_team'), 'users', ['team'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_team'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_latest_task'), table_name='users')
    op.alter_column('users', 'team',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_description'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_day'), table_name='tasks')
    op.create_unique_constraint(op.f('tasks_day_title_key'), 'tasks', ['day', 'title'], postgresql_nulls_not_distinct=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_index(op.f('ix_task_status_user_id'), table_name='task_status')
    op.drop_index(op.f('ix_task_status_task_no'), table_name='task_status')
    op.drop_index(op.f('ix_task_status_status'), table_name='task_status')
    op.drop_index(op.f('ix_task_status_log_id'), table_name='task_status')
    op.alter_column('task_status', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('task_status', 'task_no',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_status', 'log_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_daily_tasks_task_no'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_task'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_day'), table_name='daily_tasks')
    op.alter_column('daily_tasks', 'day',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('test_table',
    sa.Column('task_no', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test_column', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['day'], ['tasks.day'], name=op.f('test_table_day_fkey')),
    sa.PrimaryKeyConstraint('task_no', name=op.f('test_table_pkey'))
    )
    op.create_index(op.f('ix_test_table_task_no'), 'test_table', ['task_no'], unique=False)
    op.create_index(op.f('ix_test_table_task'), 'test_table', ['task'], unique=False)
    op.create_index(op.f('ix_test_table_day'), 'test_table', ['day'], unique=False)
    op.drop_table('company')
    # ### end Alembic commands ###
