"""adding address column to company

Revision ID: f334f4aecbe9
Revises: 7e4d36bd3e4a
Create Date: 2025-06-20 16:30:24.131782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f334f4aecbe9'
down_revision: Union[str, Sequence[str], None] = '7e4d36bd3e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('address', sa.String(length=20), nullable=False))
    op.alter_column('company', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('company', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('company', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('company', 'address')
    # ### end Alembic commands ###
