"""Add search_vector to tasks

Revision ID: 5168ac5473c9
Revises: d495ddc2a667
Create Date: 2025-06-20 18:12:07.922518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5168ac5473c9'
down_revision: Union[str, Sequence[str], None] = 'd495ddc2a667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersname')
    op.drop_table('accounts')
    op.add_column('tasks', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_tasks_search_vector', 'tasks', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_search_vector', table_name='tasks', postgresql_using='gin')
    op.drop_column('tasks', 'search_vector')
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey'))
    )
    op.create_table('usersname',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usersname_pkey')),
    sa.UniqueConstraint('name', name=op.f('usersname_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
