"""checking after column add

Revision ID: 7b6e8ca2af78
Revises: 687191d70b7a
Create Date: 2025-06-23 18:57:02.583336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6e8ca2af78'
down_revision: Union[str, Sequence[str], None] = '687191d70b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'team')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('team', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
