"""adding autogenerate migration

Revision ID: af4dcfac22c7
Revises: e051c71326d2
Create Date: 2025-06-20 15:42:19.244933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4dcfac22c7'
down_revision: Union[str, Sequence[str], None] = 'e051c71326d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_table('task_status')
    op.drop_table('daily_tasks')
    op.drop_index(op.f('ix_test_table_day'), table_name='test_table')
    op.drop_index(op.f('ix_test_table_task'), table_name='test_table')
    op.drop_index(op.f('ix_test_table_task_no'), table_name='test_table')
    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('task_no', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test_column', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['day'], ['tasks.day'], name=op.f('test_table_day_fkey')),
    sa.PrimaryKeyConstraint('task_no', name=op.f('test_table_pkey'))
    )
    op.create_index(op.f('ix_test_table_task_no'), 'test_table', ['task_no'], unique=False)
    op.create_index(op.f('ix_test_table_task'), 'test_table', ['task'], unique=False)
    op.create_index(op.f('ix_test_table_day'), 'test_table', ['day'], unique=False)
    op.create_table('daily_tasks',
    sa.Column('task_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['day'], ['tasks.day'], name='daily_tasks_day_fkey'),
    sa.PrimaryKeyConstraint('task_no', name='daily_tasks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('task_status',
    sa.Column('task_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('log_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['task_no'], ['daily_tasks.task_no'], name=op.f('task_status_task_no_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('task_status_user_id_fkey')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('task_status_pkey'))
    )
    op.create_table('tasks',
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('day', name='tasks_pkey'),
    sa.UniqueConstraint('day', 'title', name='tasks_day_title_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('team', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('latest_task', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['latest_task'], ['daily_tasks.task_no'], name=op.f('users_latest_task_fkey')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('users_pkey'))
    )
    op.drop_table('company')
    # ### end Alembic commands ###
